#!/bin/bash

#reset script from Adrian.

# kcminputrc

kwriteconfig --file ~/.config/kcminputrc --group Mouse --key cursorTheme breeze_cursors



# kdeglobals

kwriteconfig --file ~/.config/kdeglobals --group General --key BrowserApplication firefox.desktop

kwriteconfig --file ~/.config/kdeglobals --group General --key ColorScheme Breeze

kwriteconfig --file ~/.config/kdeglobals --group General --key Name Breeze

kwriteconfig --file ~/.config/kdeglobals --group General --key shadeSortColumn true

kwriteconfig --file ~/.config/kdeglobals --group General --key widgetStyle Breeze

kwriteconfig --file ~/.config/kdeglobals --group General --key XftAntialias true

kwriteconfig --file ~/.config/kdeglobals --group General --key XftHintStyle hintslight

kwriteconfig --file ~/.config/kdeglobals --group General --key XftSubPixel rgb

kwriteconfig --file ~/.config/kdeglobals --group KDE --key ColorScheme Breeze

kwriteconfig --file ~/.config/kdeglobals --group KDE --key LookAndFeelPackage org.kde.breeze.desktop

kwriteconfig --file ~/.config/kdeglobals --group KDE --key contrast 4

kwriteconfig --file ~/.config/kdeglobals --group KDE --key widgetStyle breeze

kwriteconfig5 --group KDE --key SingleClick true



# kglobalshortcutsrc

kwriteconfig --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key NewTab ",none,Open a New Tab"

kwriteconfig --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key NewWindow "none,none,Open a New Window"

kwriteconfig --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key _k_friendly_name "Launch Konsole"

kwriteconfig --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key _launch "Ctrl+Alt+T,none,Launch Konsole"

kwriteconfig --file ~/.config/kglobalshortcutsrc --group yakuake --key _k_friendly_name Yakuake

kwriteconfig --file ~/.config/kglobalshortcutsrc --group yakuake --key toggle-window-state "F4,F12,Open/Retract Yakuake"



# klaunchrc

kwriteconfig --file ~/.config/klaunchrc --group BusyCursorSettings --key Blinking false

kwriteconfig --file ~/.config/klaunchrc --group BusyCursorSettings --key Bouncing false

kwriteconfig --file ~/.config/klaunchrc --group BusyCursorSettings --key Timeout 4

kwriteconfig --file ~/.config/klaunchrc --group FeedbackStyle --key BusyCursor true

kwriteconfig --file ~/.config/klaunchrc --group FeedbackStyle --key TaskbarButton true

kwriteconfig --file ~/.config/klaunchrc --group TaskbarButtonSettings --key Timeout 4



# komparerc

kwriteconfig --file ~/.config/komparerc --group "Diff Options" --key DiffProgram /usr/bin/diff



# kscreenlockerrc

kwriteconfig --file ~/.config/kscreenlockerrc --group Daemon --key Autolock false

kwriteconfig --file ~/.config/kscreenlockerrc --group Daemon --key LockOnResume false

kwriteconfig --file ~/.config/kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key Image file:///usr/share/backgrounds/mx_blue.jpg



# ksmserverrc

kwriteconfig --file ~/.config/ksmserverrc --group General --key excludeApps yakuake,conky,apt-notifier

kwriteconfig --file ~/.config/ksmserverrc --group General --key loginMode default



# ksplashrc

kwriteconfig --file ~/.config/ksplashrc --group KSplash --key Engine KSplashQML

kwriteconfig --file ~/.config/ksplashrc --group KSplash --key Theme QuarksSplashDark



# kwalletrc

kwriteconfig --file ~/.config/kwalletrc --group Wallet --key Enabled false



# kwinrc

kwriteconfig --file ~/.config/kwinrc --group Desktops --key Number 2

kwriteconfig --file ~/.config/kwinrc --group Desktops --key Rows 2

kwriteconfig --file ~/.config/kwinrc --group TabBox --key DesktopLayout org.kde.breeze.desktop

kwriteconfig --file ~/.config/kwinrc --group TabBox --key DesktopListLayout org.kde.breeze.desktop

kwriteconfig --file ~/.config/kwinrc --group TabBox --key LayoutName org.kde.breeze.desktop

kwriteconfig --file ~/.config/kwinrc --group org.kde.kdecoration2 --key library org.kde.breeze



# plasma-org.kde.plasma.desktop-appletsrc

cp /etc/skel/.config/plasma-org.kde.plasma.desktop-appletsrc ~/.config/



# plasmarc

kwriteconfig --file ~/.config/plasmarc --group Theme --key name breeze-dark

kwriteconfig --file ~/.config/plasmarc --group Wallpapers --key usersWallpapers /usr/share/backgrounds/mx_blue.jpg



# yakuakerc

kwriteconfig --file ~/.config/yakuakerc --group Dialogs --key FirstRun false

kwriteconfig --file ~/.config/yakuakerc --group Window --key KeepOpen false



# Copy autostart items

cp /etc/skel/.config/autostart/conky.desktop ~/.config/autostart/

cp /etc/skel/.config/autostart/org.kde.yakuake.desktop ~/.config/autostart/



# Set wallpaper

qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file:///usr/share/backgrounds/mx_blue.jpg")}'

sleep 2

exit 0
