#!/bin/bash

#reset script from Adrian.

# kcminputrc

kwriteconfig5 --file ~/.config/kcminputrc --group Mouse --key cursorTheme breeze_cursors



# kdeglobals

kwriteconfig5 --file ~/.config/kdeglobals --group General --key BrowserApplication firefox.desktop

kwriteconfig5 --file ~/.config/kdeglobals --group General --key Name MX-Comfort-Breeze

kwriteconfig5 --file ~/.config/kdeglobals --group General --key ColorScheme MXcomfortbreeze

kwriteconfig5 --file ~/.config/kdeglobals --group Icons --key Theme Papirus-mxblue-darkpanes

kwriteconfig5 --file ~/.config/kdeglobals --group General --key shadeSortColumn true

kwriteconfig5 --file ~/.config/kdeglobals --group General --key XftAntialias true

kwriteconfig5 --file ~/.config/kdeglobals --group General --key XftHintStyle hintslight

kwriteconfig5 --file ~/.config/kdeglobals --group General --key XftSubPixel rgb

kwriteconfig5 --file ~/.config/kdeglobals --group KDE --key LookAndFeelPackage org.mxlinux.mx.desktop

kwriteconfig5 --file ~/.config/kdeglobals --group KDE --key contrast 4

kwriteconfig5 --group KDE --key SingleClick true



# kglobalshortcutsrc

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key NewTab ",none,Open a New Tab"

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key NewWindow "none,none,Open a New Window"

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key _k_friendly_name "Launch Konsole"

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key _launch "Ctrl+Alt+T,none,Launch Konsole"

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group yakuake --key _k_friendly_name Yakuake

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group yakuake --key toggle-window-state "F4,F12,Open/Retract Yakuake"



# klaunchrc

kwriteconfig5 --file ~/.config/klaunchrc --group BusyCursorSettings --key Blinking false

kwriteconfig5 --file ~/.config/klaunchrc --group BusyCursorSettings --key Bouncing false

kwriteconfig5 --file ~/.config/klaunchrc --group BusyCursorSettings --key Timeout 4

kwriteconfig5 --file ~/.config/klaunchrc --group FeedbackStyle --key BusyCursor true

kwriteconfig5 --file ~/.config/klaunchrc --group FeedbackStyle --key TaskbarButton true

kwriteconfig5 --file ~/.config/klaunchrc --group TaskbarButtonSettings --key Timeout 4



# komparerc

kwriteconfig5 --file ~/.config/komparerc --group "Diff Options" --key DiffProgram /usr/bin/diff



# kscreenlockerrc

kwriteconfig5 --file ~/.config/kscreenlockerrc --group Daemon --key Autolock false

kwriteconfig5 --file ~/.config/kscreenlockerrc --group Daemon --key LockOnResume false

kwriteconfig5 --file ~/.config/kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key Image file:///usr/share/backgrounds/mx_blue.jpg



# ksmserverrc

kwriteconfig5 --file ~/.config/ksmserverrc --group General --key excludeApps yakuake,conky,apt-notifier

kwriteconfig5 --file ~/.config/ksmserverrc --group General --key loginMode default



# ksplashrc

kwriteconfig5 --file ~/.config/ksplashrc --group KSplash --key Engine KSplashQML

kwriteconfig5 --file ~/.config/ksplashrc --group KSplash --key Theme QuarksSplashDark



# kwalletrc

kwriteconfig5 --file ~/.config/kwalletrc --group Wallet --key Enabled false



# kwinrc

kwriteconfig5 --file ~/.config/kwinrc --group Desktops --key Number 2

kwriteconfig5 --file ~/.config/kwinrc --group Desktops --key Rows 2

kwriteconfig5 --file ~/.config/kwinrc --group TabBox --key DesktopLayout org.kde.breeze.desktop

kwriteconfig5 --file ~/.config/kwinrc --group TabBox --key DesktopListLayout org.kde.breeze.desktop

kwriteconfig5 --file ~/.config/kwinrc --group TabBox --key LayoutName org.kde.breeze.desktop



# plasma-org.kde.plasma.desktop-appletsrc

cp /etc/skel/.config/plasma-org.kde.plasma.desktop-appletsrc ~/.config/


# yakuakerc

kwriteconfig5 --file ~/.config/yakuakerc --group Dialogs --key FirstRun false

kwriteconfig5 --file ~/.config/yakuakerc --group Window --key KeepOpen false



# Copy autostart items

cp /etc/skel/.config/autostart/conky.desktop ~/.config/autostart/

cp /etc/skel/.config/autostart/org.kde.yakuake.desktop ~/.config/autostart/

sleep 2

exit 0
