#!/bin/bash

#reset script from Adrian.

# kcminputrc

kwriteconfig5 --file ~/.config/kcminputrc --group Mouse --key cursorTheme breeze_cursors



# kdeglobals

kwriteconfig5 --file ~/.config/kdeglobals --group General --key BrowserApplication firefox.desktop

kwriteconfig5 --file ~/.config/kdeglobals --group General --key Name MX-Comfort-Breeze

kwriteconfig5 --file ~/.config/kdeglobals --group General --key ColorScheme MXcomfortbreeze

kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Disabled --key Color 56,56,56
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Disabled --key ColorAmount 0
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Disabled --key ColorEffect 0
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Disabled --key ContrastAmount 0.65
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Disabled --key ContrastEffect 1
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Disabled --key IntensityAmount 0.1
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Disabled --key IntensityEffect 2

kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Inactive --key Color 112,111,110
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Inactive --key ColorAmount 0.25
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Inactive --key ColorEffect 2
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Inactive --key ContrastAmount 0.1
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Inactive --key ContrastEffect 2
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Inactive --key IntensityAmount 0
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Inactive --key IntensityEffect 0
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Inactive --key Enable false
kwriteconfig5 --file ~/.config/kdeglobals --group ColorEffects:Inactive --key ChangeSelectionColor true

kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key BackgroundAlternate 189,195,199
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key BackgroundNormal=239,240,241
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key DecorationFocus=18,102,249
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key DecorationHover=15,86,217
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key ForegroundActive=61,174,233
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key ForegroundInactive=127,140,141
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key ForegroundLink=41,128,185
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key ForegroundNegative=218,68,83
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key ForegroundNeutral=246,116,0
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key ForegroundNormal=0,0,0
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key ForegroundPositive=39,174,96
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Button --key ForegroundVisited=127,140,141

kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --key BackgroundAlternate=59,64,69
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --key BackgroundNormal=49,54,59
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --key DecorationFocus=30,146,255
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --keyDecorationHover=61,174,230
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --key ForegroundActive=147,206,233
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --key ForegroundInactive=175,176,179
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --key ForegroundLink=61,174,230
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --key ForegroundNegative=231,76,60
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --key ForegroundNeutral=253,188,75
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --key ForegroundNormal=239,240,241
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --key ForegroundPositive=46,204,113
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Complementary --key ForegroundVisited=61,174,230

kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key BackgroundAlternate=29,153,243
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key BackgroundNormal=15,86,217
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key DecorationFocus=18,102,249
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key DecorationHover=15,86,217
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key ForegroundActive=252,252,252
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key ForegroundInactive=239,240,241
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key ForegroundLink=253,188,75
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key ForegroundNegative=218,68,83
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key ForegroundNeutral=246,116,0
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key ForegroundNormal=252,252,252
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key ForegroundPositive=39,174,96
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Selection --key ForegroundVisited=189,195,199

kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key BackgroundAlternate=77,77,77
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key BackgroundNormal=35,38,39
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key DecorationFocus=18,102,249
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key DecorationHover=15,86,217
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key ForegroundActive=61,174,233
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key ForegroundInactive=189,195,199
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key ForegroundLink=41,128,185
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key ForegroundNegative=218,68,83
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key ForegroundNeutral=246,116,0
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key ForegroundNormal=252,252,252
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key ForegroundPositive=39,174,96
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Tooltip --key ForegroundVisited=127,140,141=

kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key BackgroundAlternate=239,240,241
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key BackgroundNormal=252,252,252
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key DecorationFocus=18,102,249
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key DecorationHover=15,86,217
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key ForegroundActive=61,174,233
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key ForegroundInactive=127,140,141
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key ForegroundLink=41,128,185
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key ForegroundNegative=218,68,83
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key ForegroundNeutral=246,116,0
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key ForegroundNormal=0,0,0
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key ForegroundPositive=39,174,96
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:View --key ForegroundVisited=127,140,141

kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key BackgroundAlternate=189,195,199
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key BackgroundNormal=239,240,241
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key DecorationFocus=18,102,249
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key DecorationHover=15,86,217
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key ForegroundActive=61,174,233
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key ForegroundInactive=127,140,141
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key ForegroundLink=41,128,185
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key ForegroundNegative=218,68,83
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key ForegroundNeutral=246,116,0
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key ForegroundNormal=0,0,0
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key ForegroundPositive=39,174,96
kwriteconfig5 --file ~/.config/kdeglobals --group Colors:Window --key ForegroundVisited=127,140,141

kwriteconfig5 --file ~/.config/kdeglobals --group Icons --key Theme Papirus-mxblue-darkpanes

kwriteconfig5 --file ~/.config/kdeglobals --group General --key shadeSortColumn true

kwriteconfig5 --file ~/.config/kdeglobals --group General --key XftAntialias true

kwriteconfig5 --file ~/.config/kdeglobals --group General --key XftHintStyle hintslight

kwriteconfig5 --file ~/.config/kdeglobals --group General --key XftSubPixel rgb

kwriteconfig5 --file ~/.config/kdeglobals --group KDE --key LookAndFeelPackage org.mxlinux.mx.desktop

kwriteconfig5 --file ~/.config/kdeglobals --group KDE --key contrast 4

kwriteconfig5 --group KDE --key SingleClick true



# kglobalshortcutsrc

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key NewTab ",none,Open a New Tab"

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key NewWindow "none,none,Open a New Window"

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key _k_friendly_name "Launch Konsole"

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group org.kde.konsole.desktop --key _launch "Ctrl+Alt+T,none,Launch Konsole"

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group yakuake --key _k_friendly_name Yakuake

kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group yakuake --key toggle-window-state "F4,F12,Open/Retract Yakuake"



# klaunchrc

kwriteconfig5 --file ~/.config/klaunchrc --group BusyCursorSettings --key Blinking false

kwriteconfig5 --file ~/.config/klaunchrc --group BusyCursorSettings --key Bouncing false

kwriteconfig5 --file ~/.config/klaunchrc --group BusyCursorSettings --key Timeout 4

kwriteconfig5 --file ~/.config/klaunchrc --group FeedbackStyle --key BusyCursor true

kwriteconfig5 --file ~/.config/klaunchrc --group FeedbackStyle --key TaskbarButton true

kwriteconfig5 --file ~/.config/klaunchrc --group TaskbarButtonSettings --key Timeout 4



# komparerc

kwriteconfig5 --file ~/.config/komparerc --group "Diff Options" --key DiffProgram /usr/bin/diff



# kscreenlockerrc

kwriteconfig5 --file ~/.config/kscreenlockerrc --group Daemon --key Autolock false

kwriteconfig5 --file ~/.config/kscreenlockerrc --group Daemon --key LockOnResume false

kwriteconfig5 --file ~/.config/kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key Image file:///usr/share/backgrounds/mx_blue.jpg



# ksmserverrc

kwriteconfig5 --file ~/.config/ksmserverrc --group General --key excludeApps yakuake,conky,apt-notifier

kwriteconfig5 --file ~/.config/ksmserverrc --group General --key loginMode default



# ksplashrc

kwriteconfig5 --file ~/.config/ksplashrc --group KSplash --key Engine KSplashQML

kwriteconfig5 --file ~/.config/ksplashrc --group KSplash --key Theme QuarksSplashDark



# kwalletrc

kwriteconfig5 --file ~/.config/kwalletrc --group Wallet --key Enabled false



# kwinrc

kwriteconfig5 --file ~/.config/kwinrc --group Desktops --key Number 2

kwriteconfig5 --file ~/.config/kwinrc --group Desktops --key Rows 2

kwriteconfig5 --file ~/.config/kwinrc --group TabBox --key DesktopLayout org.kde.breeze.desktop

kwriteconfig5 --file ~/.config/kwinrc --group TabBox --key DesktopListLayout org.kde.breeze.desktop

kwriteconfig5 --file ~/.config/kwinrc --group TabBox --key LayoutName org.kde.breeze.desktop



# plasma-org.kde.plasma.desktop-appletsrc

cp /etc/skel/.config/plasma-org.kde.plasma.desktop-appletsrc ~/.config/


# yakuakerc

kwriteconfig5 --file ~/.config/yakuakerc --group Dialogs --key FirstRun false

kwriteconfig5 --file ~/.config/yakuakerc --group Window --key KeepOpen false



# Copy autostart items

cp /etc/skel/.config/autostart/conky.desktop ~/.config/autostart/

cp /etc/skel/.config/autostart/org.kde.yakuake.desktop ~/.config/autostart/

sleep 2

exit 0
