#! /bin/sh

set -e

#cleanup some old configs from bullseye/buster
if [ -e  /etc/polkit-1/localauthority.conf.d/55-tweak-override.conf ]; then
	rm /etc/polkit-1/localauthority.conf.d/55-tweak-override.conf
fi

exit 0
