#! /bin/sh

set -e

#if 55-tweak-override not present, assume root account is selected
if [ ! -e  /etc/poklit-1/localauthority.conf.d/55-tweak-override.conf ]; then
	if [ ! -e /etc/polkit-1/rules.d/10-default-mx.rules ]; then
  		cp /usr/share/mx-tweak/10-default-mx.rules /etc/polkit-1/rules.d/10-default-mx.rules
	fi
fi

exit 0
